menu:
  首页: /
  历史文章: /archives
  碎碎念: /memos
  关于我: /about

social:
  GitHub: https://github.com/Wunala
  Email: mailto:youngqi27@163.com

profile:
  name: 读读说明书
  subtitle: 数据分析师 | 生活科学家
  motto: 在夏天到达的尽头，值得我赌上每一份青春。
